export const CHAT_EVENTS = {
  // Client -> Server
  JOIN_ROOM: 'join_room',
  SEND_MESSAGE: 'send_message',
  SEND_IMAGE: 'send_image',
  SEND_VOICE: 'send_voice',
  DELETE_MESSAGE: 'delete_message',
  EDIT_MESSAGE: 'edit_message',
  MESSAGE_REACTION: 'message_reaction',
  PIN_MESSAGE: 'pin_message',
  UNPIN_MESSAGE: 'unpin_message',
  MESSAGE_READ: 'message_read',
  LOAD_MESSAGE_CONTEXT: 'load_message_context',
  TYPING_START: 'typing_start',
  TYPING_STOP: 'typing_stop',
  GET_PINNED_MESSAGES: 'get_pinned_messages',
  ADMIN_SUBSCRIBE: 'admin:subscribe',

  // Server -> Client
  JOIN_ERROR: 'join_error',
  CHAT_HISTORY: 'chat_history',
  RECEIVE_MESSAGE: 'receive_message',
  RECEIVE_IMAGE: 'receive_image',
  RECEIVE_VOICE: 'receive_voice',
  UPDATE_USERS: 'update_users',
  USER_TYPING: 'user_typing',
  UPDATE_REACTION: 'update_reaction',
  IMAGE_ERROR: 'image_error',
  VOICE_ERROR: 'voice_error',
  MESSAGE_DELETED: 'message_deleted',
  DELETE_ERROR: 'delete_error',
  MESSAGE_EDITED: 'message_edited',
  EDIT_ERROR: 'edit_error',
  MESSAGE_CONTEXT: 'message_context',
  MESSAGE_CONTEXT_ERROR: 'message_context_error',
  PINNED_MESSAGES_LIST: 'pinned_messages_list',
  MESSAGE_PINNED: 'message_pinned',
  MESSAGE_UNPINNED: 'message_unpinned',
  RECEIPTS_UPDATED: 'receipts_updated',
  USER_PROFILE_UPDATED: 'user_profile_updated',
  ADMIN_STATS: 'admin:stats',
  ADMIN_ERROR: 'admin:error',
};

export default CHAT_EVENTS;
